### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by nclundsten** [sedabull/quantum-shell#13]
/home/nlundsten/.atom/packages/quantum-shell/lib/quantum-shell-model.coffee:192
Hide Stack Trace
TypeError: undefined is not a function
  at QuantumShellModel.promptString (/home/nlundsten/.atom/packages/quantum-shell/lib/quantum-shell-model.coffee:195:83)
  at /home/nlundsten/.atom/packages/quantum-shell/lib/quantum-shell-controller.coffee:191:83

**Comment by hoosierhobbyist** [comment]
Thank you for the bug report. This should be fixed now, however if you're still having an issue with it after upgrading to 0.6.1, please reopen this and let me know.
